config/routes.rb
Rails.application.routes.draw do
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
 skip_before_filter :verify_authenticity_token

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
	respond_to do |format|
		format.json { render json: @cars }
		format.html
	end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.json { render :show, status: :created, location: @car }
      else
        # format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
	redirect_to :index
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
	
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:Manufacturer, :Model, :Consumption, :Colour, :YearOfRelease, :Doors, :URL)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(car, remote: true) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Manufacturer %>
    <%= f.text_field :Manufacturer %>
  </div>

  <div class="field">
    <%= f.label :Model %>
    <%= f.text_field :Model %>
  </div>

  <div class="field">
    <%= f.label :Consumption %>
    <%= f.text_field :Consumption %>
  </div>

  <div class="field">
    <%= f.label :Colour %>
    <%= f.text_field :Colour %>
  </div>

  <div class="field">
    <%= f.label :YearOfRelease %>
    <%= f.number_field :YearOfRelease %>
  </div>

  <div class="field">
    <%= f.label :Doors %>
    <%= f.number_field :Doors %>
  </div>

  <div class="field">
    <%= f.label :URL %>
    <%= f.text_field :URL %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<img src="http://mbmfiles.com/Jun2017/170622-1mvHpADc-d_C.png" />

<% @cars.each do |car| %>
    <table cellpadding="0px" cellspacing="20px">
      <thead>
        <tr>
          <th>Manufacturer</th>
          <th>Model</th>
          <th>FuelConsumption</th>
          <th>Colour</th>
          <th>YearOfRelease</th>
          <th>DoorsCount</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= car.Manufacturer %></td>
            <td><%= car.Model %></td>
            <td><%= car.Consumption %></td>
            <td><%= car.Colour %></td>
            <td><%= car.YearOfRelease %></td>
            <td><%= car.Doors %> <style media="screen">
            </style></td>
            <td><%= link_to 'Show', car %></td>
            <td><%= link_to 'Edit', edit_car_path(car) %></td>
            <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      </tbody>
    </table>
    <img src="<%= car.URL %>" width="50%" height="50%" />
<% end %>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.Manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.Model %>
</p>

<p>
  <strong>Consumption:</strong>
  <%= @car.Consumption %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @car.Colour %>
</p>

<p>
  <strong>Year Of Release:</strong>
  <%= @car.YearOfRelease %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @car.Doors %>
</p>

<p>
  <strong>Image provided:</strong><br>
  <img src="<%= @car.URL %>" width="50%" height="50%" />
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsCatalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>